export const EASTWEST_REFERENCE_REPORT = {
  proofLabel: 'Reference-layout proof',
  clientLogoAlt: 'EastWest logo reference crop',
  preparedByLogoAlt: 'Praxis Experiential logo reference crop',
  cover: {
    title: 'Social Monitoring Report',
    period: 'August 14-20, 2026',
    preparedBy: 'Prepared by:',
  },
  sectionTitle: 'EastWest Bank\nSentiment Score Report',
  previousReportSummary: {
    title: 'Previous Report Summary',
    items: [
      {
        lead: 'Total mentions',
        body: 'reached 2.99k with the largest spikes on August 13 were caused by users talking about certain EastWest products, specifically their credit cards, home loans, and personal loans. The bank also pushed digital and transactional convenience through EasyWay foreign exchange, home loan rates, and app-based banking features. recent partnerships, industry recognitions, and EastWest Dream Run Manila.',
      },
      {
        lead: 'Positive Drivers',
        body: 'include news releases about EastWest Dream Run 2026 heads to Clark for the second stop of its four-leg race series, giving participants a unique running experience. Additionally, EastWest has partnered with DragonFi Securities, Inc. and Luna Securities, Inc. to expand access to its Personal Equity and Retirement Account (PERA) products. Honda Cars Philippines, Inc. (HCPI) is making the HR-V more affordable this month by providing more accessible low monthly amortizations, low all-in downpayment rates, and other flexible financing options through EastWest Bank',
      },
      {
        lead: 'Negative Themes',
        body: "were mainly complaints from users as they've experienced payment errors with their credit cards, ESTA chatbot and app not working and not accessible to users.",
      },
      {
        lead: 'Scam-Related Risks',
        body: "- impersonation scams continue to pose a major risk to EastWest Bank's brand trust, appearing as fake rewards, fraudulent calls and texts and even emails, and smishing tactics and attempts.",
      },
      {
        lead: 'Channel Dynamics',
        body: "- Reddit still remains a key platform for financial conversations, with users sharing both positive and critical experiences with EastWest Bank's services. X is also becoming an active platform for users to engage in conversations about the bank's products and services.",
      },
      {
        lead: 'Competitor Landscape',
        body: '-',
        subitems: [
          'News releases about events, ongoing or upcoming partnerships and collaborations, and even achievements continue to increase online engagements',
          'Concerns like scams, fraud, and app issues continue to highlight opportunities to improve customer experience and security.',
        ],
      },
    ],
  },
  metricsPages: [
    {
      referencePage: 4,
      kind: 'mentions',
      title: 'EW: Mentions Overview from August 14-20, 2026*',
      currentLabel: 'Current Week\n(August 14-20)',
      previousWeekLabel: 'Previous Week\n(August 7-13)',
      previousMonthLabel: 'Previous Full Month\n(July)',
      footerTitle: 'Eastwest Bank Mention Statistics Report',
      note: '*Across all platforms: FB, IG, X, Tiktok, Web, News Forums etc.',
      insight: 'EastWest conversation peaks were\ndriven by Dream Run Club\npromotions, cashback/travel offers,\nand increased Credit Card inquiries.',
      comparisonTitle: 'Overview Comparisons',
      chartDataState: 'approved_image_fallback_raw_daily_series_unavailable',
      charts: {
        current: {
          dataState: 'approved_image_fallback',
          fallbackAsset: 'mentionsMain',
          metricTotals: [
            { label: 'Total Mentions', value: '2.66K', comparison: 'Previous period 3.01K', change: '-11.6%' },
            { label: 'Daily Average', value: '380', comparison: 'Previous period 430', change: '-11.6%' },
          ],
          dailySeries: { dataState: 'unavailable', points: [] },
          callouts: [
            'EastWest Dream Run Club Promotions',
            'Spike in EWB Credit Card inquiries',
            'EastWest Dream Run Club (Clark) with Mogu Mogu',
            'Complaints and praises on EWB App (app updates & chatbot) through Reddit posts',
            'Multiple Retail Sellers put EWB as a payment channel in their listings',
            'EWB Cashback offers, travel promos, and operational notices due to the weather',
            'Retailers promoting installment payment option tied to EWB',
          ],
        },
        previousWeek: {
          dataState: 'approved_image_fallback',
          fallbackAsset: 'mentionsPreviousWeek',
          metricTotals: [
            { label: 'Total Mentions', value: '3.01K' },
            { label: 'Daily Average', value: '430' },
          ],
          dailySeries: { dataState: 'unavailable', points: [] },
        },
        previousMonth: {
          dataState: 'approved_image_fallback',
          fallbackAsset: 'mentionsPreviousMonth',
          metricTotals: [
            { label: 'Total Mentions', value: '168K' },
            { label: 'Daily Average', value: '5.43K' },
          ],
          dailySeries: { dataState: 'unavailable', points: [] },
        },
      },
      images: {
        main: 'mentionsMain',
        previousWeek: 'mentionsPreviousWeek',
        previousMonth: 'mentionsPreviousMonth',
      },
    },
    {
      referencePage: 5,
      kind: 'source',
      title: 'EW: Mentions by Source Type from August 14-20 2026*',
      currentLabel: 'Current Week\n(August 14-20)',
      previousWeekLabel: 'Previous Week\n(August 7-13)',
      previousMonthLabel: 'Previous Full Month\n(July)',
      footerTitle: 'Eastwest Bank Mention Statistics Report',
      note: '*Across all platforms: FB, IG, X, Tiktok, Web, News Forums etc.',
      insight: 'Reddit and Facebook continued to contribute to ongoing conversations,\nbut X is increasingly emerging as the key platform driving\nconversation spikes. Activity peaked on Aug 17 (~630 mentions) and\nagain on Aug 19 (~540), suggesting that timely topics are gaining\nstronger traction and prompting more immediate, high-volume\ndiscussions on X.',
      comparisonTitle: 'Overview Comparisons',
      chartDataState: 'approved_image_fallback_raw_daily_source_series_unavailable',
      charts: {
        current: {
          dataState: 'approved_image_fallback',
          fallbackAsset: 'sourceMain',
          metricTotals: [
            { label: 'All', value: '2.66K' },
            { label: 'X', value: '1.43K' },
            { label: 'Reddit', value: '609' },
            { label: 'Facebook', value: '455' },
            { label: 'YouTube', value: '82' },
            { label: 'News - Online', value: '55' },
            { label: 'Blogs', value: '17' },
            { label: 'Instagram', value: '15' },
            { label: 'Forums', value: '1' },
          ],
          sourceSeries: { dataState: 'unavailable', points: [] },
        },
        previousWeek: {
          dataState: 'approved_image_fallback',
          fallbackAsset: 'sourcePreviousWeek',
          sourceSeries: { dataState: 'unavailable', points: [] },
        },
        previousMonth: {
          dataState: 'approved_image_fallback',
          fallbackAsset: 'sourcePreviousMonth',
          sourceSeries: { dataState: 'unavailable', points: [] },
        },
      },
      images: {
        main: 'sourceMain',
        previousWeek: 'sourcePreviousWeek',
        previousMonth: 'sourcePreviousMonth',
      },
    },
    {
      referencePage: 6,
      kind: 'reach',
      title: 'EW: Reach from August 14-20, 2026*',
      currentLabel: 'Current Week\n(August 14-20)',
      previousWeekLabel: 'Previous Week\n(August 7-13)',
      previousMonthLabel: 'Previous Full Month\n(July)',
      footerTitle: 'Eastwest Bank Reach Statistics Report',
      note: '*Across all platforms: FB, IG, X, Tiktok, Web, News Forums etc.',
      insight: 'EastWest Dream Run Emerges as the\nStrongest Reach Driver, While\nCommunity and Financial Literacy\nInitiatives Sustain Broader Visibility',
      comparisonTitle: 'Overview Comparisons',
      chartDataState: 'approved_image_fallback_raw_daily_reach_series_unavailable',
      charts: {
        current: {
          dataState: 'approved_image_fallback',
          fallbackAsset: 'reachMain',
          metricTotals: [
            { label: 'Total Reach', value: '380M', comparison: 'Previous period 454M', change: '-16.4%' },
            { label: 'Daily Average', value: '54.3M', comparison: 'Previous period 64.9M', change: '-16.4%' },
          ],
          dailySeries: { dataState: 'unavailable', points: [] },
          callouts: [
            'The most engaged posts promote the EastWest Dream Run 2026',
            'Dream Run stops in Iloilo and Clark.',
            'EastWest Dream Run 2026 Clark leg',
            'financial literacy campus talk in Polytechnic University',
            'EWB Mentioned in Hamungaya Feast Street Festival 2026',
          ],
        },
        previousWeek: {
          dataState: 'approved_image_fallback',
          fallbackAsset: 'reachPreviousWeek',
          metricTotals: [
            { label: 'Total Reach', value: '454M' },
            { label: 'Daily Average', value: '64.9M' },
          ],
          dailySeries: { dataState: 'unavailable', points: [] },
        },
        previousMonth: {
          dataState: 'approved_image_fallback',
          fallbackAsset: 'reachPreviousMonth',
          metricTotals: [
            { label: 'Total Reach', value: '1.36B' },
            { label: 'Daily Average', value: '44M' },
          ],
          dailySeries: { dataState: 'unavailable', points: [] },
        },
      },
      images: {
        main: 'reachMain',
        previousWeek: 'reachPreviousWeek',
        previousMonth: 'reachPreviousMonth',
      },
    },
  ],
  sentimentPage: {
    title: 'EW: Sentiment Score from August 14-20, 2026*',
    statement: 'Positive sentiment declined vs. the previous period, but\nremained driven by community, customer, and credibility\ninitiatives, while negative conversations continued to flag\nsecurity and service concerns.',
    comparisonTitle: 'Overview Comparisons',
    currentLabel: 'Current Week\n(August 14-20)',
    previousWeekLabel: 'Previous Week\n(August 7-13)',
    previousMonthLabel: 'Previous Full Month\n(July)',
    footerTitle: 'Eastwest Bank Sentiment Score Report',
    note: '*Across all platforms: FB, IG, X, Tiktok, Web, News Forums etc.',
    current: {
      neutral: { label: 'Neutral', value: '1.63K', percent: '61.2%', size: 61.2 },
      negative: { label: 'Negative', value: '665', percent: '25.0%', size: 25.0 },
      positive: { label: 'Positive', value: '368', percent: '13.8%', size: 13.8 },
    },
    previousWeek: {
      neutral: { label: 'Neutral', value: '1.95K', percent: '64.8%', size: 64.8 },
      negative: { label: 'Negative', value: '628', percent: '20.8%', size: 20.8 },
      positive: { label: 'Positive', value: '431', percent: '14.3%', size: 14.3 },
    },
    previousMonth: {
      neutral: { label: 'Neutral', value: '85.1K', percent: '50.5%', size: 50.5 },
      positive: { label: 'Positive', value: '43.8K', percent: '26.0%', size: 26.0 },
      negative: { label: 'Negative', value: '39.6K', percent: '23.5%', size: 23.5 },
    },
  },
  evidencePages: [
    {
      referencePage: 8,
      tone: 'positive',
      title: 'EW: Positive Sentiments from August 14-20, 2026',
      summaryMetric: { label: 'Positive', value: '368', percent: '13.8%' },
      statement: 'Positive conversations around\nEastWest were driven by initiatives\nthat reinforce the bank as a\ncustomer-centric and credible\nfinancial partner: from empowering\ncommunities through the Dream\nRun, rewarding customers through\nHot Deals, strengthening credibility\nthrough international awards, and\nexpanding access to digital\nretirement investing.',
      cards: [
        {
          asset: 'positiveDreamRun',
          className: 'ew-card-wide',
          reach: '408.83K Reach, 2.04K Views',
          link: 'Link',
          text: 'EastWest Dream Run 2026. The Manila kickoff generated positive editorial coverage by combining a sold-out race, family participation, and inspiring women and mothers on the podium.',
        },
        {
          asset: 'positiveHotDeals',
          className: 'ew-card-small',
          reach: '80.9K Reach, 1.22K Views',
          link: 'Link',
          text: 'EastWest Hot Deals Raffle Promo: Frames Eastwest as a generous bank. It highlights the intention of the promo which is to push clients to achieve their financial goals.',
        },
        {
          asset: 'positiveAwards',
          className: 'ew-card-tall',
          reach: '5.05K Reach, 12K Views',
          link: 'Link',
          text: "EastWest Bank wins dual international finance awards: The article celebrates EastWest's awards and how this event ties up to the bank's credibility",
        },
        {
          asset: 'positiveRetirement',
          className: 'ew-card-tall',
          reach: '3.55K Reach, 63K Views',
          link: 'Link',
          text: "EastWest Expands Digital Access to Retirement Investing: Highlights EastWest's efforts for improvement and reachability to its clients.",
        },
      ],
    },
    {
      referencePage: 9,
      tone: 'negative',
      title: 'EW: Negative Sentiments from August 14-20, 2026',
      summaryMetric: { label: 'Negative', value: '665', percent: '25.0%' },
      statement: 'Negative sentiment largely\ncentered on concerns around\nsecurity and customer service,\nwith scam-related incidents and\nunauthorized transactions\nraising doubts about EastWest’s\nfraud protection, while slow\nassistance and credit card hold\ntimes further contributed to\ncustomer frustration.',
      cards: [
        {
          asset: 'negativeScamText',
          className: 'ew-card-wide',
          reach: '282.59K Reach',
          link: 'Link',
          text: 'Victim of Scam By Text: Netizens express their experience on receiving a text from EWB then immediately gets their money',
        },
        {
          asset: 'negativeCustomerService',
          className: 'ew-card-wide',
          reach: '92.06K Reach',
          link: 'Link',
          text: 'Customer Service concern: Sentiments on slow and unproficient customer service',
        },
        {
          asset: 'negativeCardHold',
          className: 'ew-card-wide',
          reach: '',
          link: 'Link',
          text: 'Credit Card on Hold: Complaints under the security tips post of EastWest specifically on CC holding timing.',
        },
        {
          asset: 'negativeUnauthorized',
          className: 'ew-card-wide-short',
          reach: '282.39K Reach',
          link: 'Link',
          text: "EastWest Bank Unauthorized Transactions: Netizen expresses that EastWest doesn't seem to take proper measures against scams",
        },
      ],
    },
    {
      referencePage: 10,
      tone: 'neutral',
      title: 'EW: Neutral Sentiments from August 14-20, 2026',
      summaryMetric: { label: 'Neutral', value: '1.63K', percent: '61.2%' },
      statement: 'Neutral Conversations\nWere Primarily Driven by\nPractical Service Inquiries,\nReflecting Customer\nInterest in Card Benefits\nand Digital Bill Payment\nFeatures.',
      cards: [
        {
          asset: 'neutralPlatinum',
          className: 'ew-card-neutral-large',
          reach: '282.59k Reach',
          link: 'Link',
          text: 'Service update: Platinum Visa over credit limit free',
        },
        {
          asset: 'neutralBills',
          className: 'ew-card-neutral-wide',
          reach: '28.53k Reach',
          link: 'Link',
          text: 'Service/feature Inquiry: How to pay bills using the platform',
        },
      ],
    },
  ],
  wordCloudPage: {
    referencePage: 11,
    title: 'EW: Word Cloud from August 14-20, 2026*',
    subtitle: 'Top Keywords This Week Centered on EastWest Bank as a Payment Option for Sellers,\nAlongside Mentions of Competitor Banks:',
    image: 'wordCloud',
    footerTitle: 'Eastwest Bank Sentiment Score Report',
    note: '*Across all platforms: FB, IG, X, Tiktok, Web, News Forums etc.',
  },
  competitorAndSovPages: [
    {
      referencePage: 12,
      type: 'sectionDivider',
      title: 'Competitor Insights\n& Share of Voice',
    },
    {
      referencePage: 13,
      type: 'competitorEvidence',
      title: 'Competitor Insight',
      pattern: 'competitor evidence grid',
      footerTitle: 'Competitor Insight',
      maxCompetitorsPerPage: 3,
      competitors: [
        {
          name: 'BPI',
          logoAsset: 'compBpiLogo',
          accent: 'red',
          positive: {
            asset: 'compBpiPositive',
            metric: '1.59k Reach',
            link: 'Link',
            caption: 'BPI NAFFL eGC campaign. No annual fee plus bonus eGCs create a strong acquisition hook.',
          },
          negative: {
            asset: 'compBpiNegative',
            metric: '282.54k Reach',
            link: 'Link',
            caption: 'BPI Credit Card App Down. App errors and unlinked cards disrupt bill payments.',
          },
        },
        {
          name: 'BDO Unibank',
          logoAsset: 'compBdoLogo',
          accent: 'gold',
          positive: {
            asset: 'compBdoPositive',
            metric: '543.12k Reach, 403 views',
            link: 'Link',
            caption: 'BDO Pay’s award recognition positions it as a practical daily-money hub, highlighting convenience and fee-free transfers.',
          },
          negative: {
            asset: 'compBdoNegative',
            metric: '808.69k Reach',
            link: 'Link',
            caption: 'Home loan posting disputes. Payment issues leave interest high and balances unclear, prompting BDO to review statements.',
          },
        },
        {
          name: 'UnionBank',
          logoAsset: 'compUnionbankLogo',
          accent: 'orange',
          positive: {
            asset: 'compUnionbankPositive',
            metric: '3.55k Reach, 63 views',
            link: 'Link',
            caption: 'Digital Walker’s 20th Anniversary pairs tech showcases with UnionBank-exclusive offers, giving the brand visible value to amplify.',
          },
          negative: {
            asset: 'compUnionbankNegative',
            metric: '282.57k Reach',
            link: 'Link',
            caption: 'UnionBank app and card setup faces failed linking, slow processing, and poor support-undermining its convenience promise.',
          },
        },
      ],
    },
    {
      referencePage: 14,
      type: 'competitorEvidence',
      title: 'Competitor Insight',
      pattern: 'competitor evidence grid continuation',
      footerTitle: 'Competitor Insight',
      maxCompetitorsPerPage: 3,
      competitors: [
        {
          name: 'Security Bank',
          logoAsset: 'compSecurityLogo',
          accent: 'cyan',
          positive: {
            asset: 'compSecurityPositive',
            metric: '78.77M Reach',
            link: 'Link',
            caption: 'H1 Earnings Surge. Security Bank’s 4% net-income growth signals disciplined growth and stronger efficiency.',
          },
          negative: {
            asset: 'compSecurityNegative',
            metric: '282.58K Reach',
            link: 'Link',
            caption: 'Security Bank missed-payment calls. Repeated calls felt like harassment, prompting some to cancel cards.',
          },
        },
        {
          name: 'Metrobank',
          logoAsset: 'compMetrobankLogo',
          accent: 'navy',
          positive: {
            asset: 'compMetrobankPositive',
            metric: '65.83K Reach',
            link: 'Link',
            caption: 'Watsons Nationwide Sale. Metrobank card discounts drove strong promo chatter, underscoring stacked savings and merchant tie-ins.',
          },
          negative: {
            asset: 'compMetrobankNegative',
            metric: '189.69K Reach',
            link: 'Link',
            caption: 'InstaPay failures. Held funds are raising concerns over Metrobank’s reliability for urgent payments.',
          },
        },
      ],
    },
    {
      referencePage: 15,
      type: 'sovMentionsCurrent',
      title: 'Share of Voice: Mentions from August 14-20, 2026*',
      pattern: 'SOV current-week chart with competitor peaks',
      footerTitle: 'SOV: Mentions',
      note: '*Across all platforms: FB, IG, X, Tiktok, Web, News Forums etc.',
      donutChartAsset: 'sovMentionsDonutCurrent',
      lineChartAsset: 'sovMentionsLineCurrent',
      chartDataState: 'approved_image_fallback',
      peakItems: [
        {
          asset: 'sovMentionsPeaksBdo',
          caption: 'BDO: BDO Pay Cash back and Bank Transfer concerns',
        },
        {
          asset: 'sovMentionsPeaksMetrobank',
          caption: 'MetroBank: Apple Pay Ad, Anti-fraud features, Preferred Bank for Cash Reward Return',
        },
      ],
    },
    {
      referencePage: 16,
      type: 'sovDonutComparison',
      title: 'Share of Voice: Mentions Comparisons',
      pattern: 'SOV comparison donut grid',
      footerTitle: 'SOV: Mentions',
      note: '*Across all platforms: FB, IG, X, Tiktok, Web, News Forums etc.',
      narrative: "EastWest's share of voice\nslipped to 10.2% this week\n(from 13% the week prior),\nwhile BDO (40.6%) and BPI\n(31.7%) both grew their share\nover the same period.\n\nZoomed out, EastWest's YTD\nshare (44.6%) and\nprevious-month share\n(61.6%) are far higher than\neither weekly cut, suggesting\nthe brand's voice is usually\ndriven by a handful of large\nmoments (e.g., Dream Run,\nproduct launches) rather\nthan sustained\nweek-to-week volume.",
      chartDataState: 'approved_image_fallback',
      charts: [
        { label: 'Current Week', asset: 'sovMentionsCompareCurrent', labelVisibility: 'image_fallback_only' },
        { label: 'Previous Full Month', asset: 'sovMentionsComparePrevMonth', labelVisibility: 'image_fallback_only' },
        { label: 'Previous Week', asset: 'sovMentionsComparePrevWeek', labelVisibility: 'image_fallback_only' },
        { label: 'YTD', asset: 'sovMentionsCompareYtd', labelVisibility: 'image_fallback_only' },
      ],
    },
    {
      referencePage: 17,
      type: 'sovSourceCurrent',
      title: 'Share of Voice: Source Type from August 14-20, 2026*',
      pattern: 'SOV source-type ranked bar chart',
      footerTitle: 'SOV: Mentions',
      note: '*Across all platforms: FB, IG, X, Tiktok, Web, News Forums etc.',
      subtitle: 'X Overtakes YouTube as the 2nd-Largest Source of Mentions, Signaling a Shift Toward More\nReal-Time Conversations and Customer Discussions on the Platform',
      chartAsset: 'sovSourceCurrent',
      chartDataState: 'approved_image_fallback',
    },
    {
      referencePage: 18,
      type: 'sovSourceComparison',
      title: 'Share of Voice: Source Type Comparisons',
      pattern: 'SOV source-type comparison grid',
      footerTitle: 'SOV: Mentions',
      note: '*Across all platforms: FB, IG, X, Tiktok, Web, News Forums etc.',
      subtitle: 'X overtook YouTube to become the #2 source of mentions this week - a change from the previous\nweek, previous month, and YTD trend, where YouTube consistently ranked above X. Facebook\nremains the dominant channel by a wide margin across every period.',
      chartDataState: 'approved_image_fallback',
      charts: [
        { label: 'Current Week', asset: 'sovSourceCompareCurrent' },
        { label: 'Previous Full Month', asset: 'sovSourceComparePrevMonth' },
        { label: 'Previous week', asset: 'sovSourceComparePrevWeek' },
        { label: 'YTD', asset: 'sovSourceCompareYtd' },
      ],
    },
  ],
  finalPages: [
    {
      referencePage: 19,
      type: 'sectionDivider',
      title: 'Final Analysis\n& Recommendations',
    },
    {
      referencePage: 20,
      type: 'reportSummary',
      title: 'Report Summary',
      items: [
        {
          lead: 'Total mentions',
          body: 'reached 2.66k, down 11.6% from the previous period, with the largest spikes on August 17 and August 19 caused by EastWest Dream Run Club promotions in Clark with Mogu Mogu, a spike in credit card inquiries, and multiple retail sellers listing EastWest as a payment and installment channel. Cashback offers, travel promos, and weather-related operational notices also added to volume.',
        },
        {
          lead: 'Positive Drivers',
          body: 'include news releases about the EastWest Dream Run 2026 Manila kickoff, which drew nearly 7,000 runners, along with EastWest winning dual international finance awards and expanding digital access to retirement investing through DragonFi Securities, Inc. and Luna Securities, Inc. The Hot Deals raffle promo, the Polytechnic University financial literacy talk, and the Hamungaya Feast Street Festival also sustained visibility.',
        },
        {
          lead: 'Negative Themes',
          body: 'were mainly complaints from users who received scam texts followed by unauthorized transactions, alongside slow customer service and credit cards placed on hold. Negative sentiment rose to 25.0% from 20.8%.',
        },
        {
          lead: 'Scam-Related Risks',
          body: '- impersonation scams continue to pose a major risk to EastWest Bank’s brand trust, appearing as fake rewards, fraudulent calls and texts and even emails, and smishing tactics and attempts. Users are also questioning whether the bank protects cardholders over merchants in disputed transactions.',
        },
        {
          lead: 'Channel Dynamics',
          body: "- X has overtaken YouTube as the second-largest source of mentions and now drives the week's conversation spikes. Reddit remains a key platform for financial conversations, particularly around the EastWest app and chatbot, while Facebook continues to deliver the widest reach.",
        },
        {
          lead: 'Competitor Landscape',
          body: '-',
          subitems: [
            "EastWest's share of voice eased to 10.2% from 13%, with Banco de Oro (40.6%) and Bank of the Philippine Islands (31.7%) continuing to lead conversation volume.",
            'Competitor positives came from promos, partnerships, and recognitions, while app errors, transfer failures, and collections practices remain shared pain points and ongoing opportunities to improve customer experience and security.',
          ],
        },
      ],
    },
    {
      referencePage: 21,
      type: 'recommendations',
      title: 'Recommendations',
      items: [
        {
          lead: 'Make fraud protection visible, not just fraud awareness',
          body: 'Scam texts and unauthorized transactions were the largest driver of negative sentiment this week, and users are beginning to question whose side the bank takes in disputed transactions. EastWest can complement its vigilance reminders by making the dispute journey clear: what happens after a report is filed, expected resolution timelines, and proactive updates to affected customers, so protection is felt and not only promised.',
        },
        {
          lead: 'Turn service recovery into a credibility proof point',
          body: 'Complaints about the app, chatbot, credit card holds, and response times were among the most visible conversations this week, concentrated on Reddit and X. Consistent, timely resolution where these concerns are raised, paired with advance notice of service changes, would help reframe a recurring negative theme as evidence of responsiveness.',
        },
        {
          lead: 'Extend the Dream Run platform between race legs',
          body: "The Dream Run remains EastWest's strongest reach driver, but visibility is concentrated on event weekends. Carrying the storyline through the remaining legs, and linking it to the financial literacy and community initiatives already earning positive coverage, would help sustain positive share of voice between events.",
        },
        {
          lead: 'Get ahead of the Platinum Visa fee update',
          body: "Neutral conversation was led by the over-credit-limit and annual membership fee changes effective August 20. Framing the update alongside the card's benefits, and equipping frontline and social teams with a single clear explanation, would keep a routine service notice from becoming a negative talking point.",
        },
      ],
    },
    {
      referencePage: 22,
      type: 'closingCover',
    },
  ],
};
